name: Build on staging

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          composer install
          npm install && npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config push.default current
          git add .
          git commit -m "build"
          git checkout -b release/staging
          git push --force

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.4
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
