name: Test on staging

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.4
        env:
          webhook_url: ${{ secrets.STAGING_DEPLOY_URL_TEST }}
          webhook_secret: ${{ secrets.STAGING_DEPLOY_SECRET }}
